title: Jingxu Gu
page-top-title: Jingxu Gu ⌈谷景旭⌋
top-section-bg-text: A Dedicated NLP & ML System Nerd Dreaming of AGI World
home-subtitle: Jingxu Gu ⌈谷景旭⌋
copyright-text: '&copy; Jingxu Gu 2025. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
